# Generated by Django 5.0.2 on 2024-12-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_comment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='User',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
    ]
