# Generated by Django 5.0.2 on 2024-12-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_comment_user_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='like_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('blog', 'User')},
        ),
    ]
