# Generated by Django 5.0.2 on 2024-12-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_likes_like_dt_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='reaction_type',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10, null=True),
        ),
    ]
